services:
  - type: web
    name: geplex-ai
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: APP_BIND
        value: 0.0.0.0
